version: 2

models:
  - name: dim_listings_cleansed
    description: >
      This model contains a cleaned version of the listings table.
    columns:
      - name: listing_id
        description: >
          The unique identifier for a listing.
        tests:
          - unique
          - not_null

      - name: host_id
        description: >
          The unique identifier for a host.
        tests:
          - not_null
          - relationships:
              to: ref('dim_hosts_cleansed')
              field: host_id

      - name: room_type
        description: >
          The type of room that is being listed.
        tests:
          - accepted_values:
              values:
                ["Entire home/apt", "Private room", "Shared room", "Hotel room"]
      - name: minimum_nights
        tests:
          - positive_value

  - name: dim_hosts_cleansed
    description: >
      This model contains a cleaned version of the hosts table.
    columns:
      - name: host_id
        description: >
          The unique identifier for a host.
        tests:
          - unique
          - not_null

      - name: host_name
        description: >
          The name of the host.
        tests:
          - not_null

      - name: is_superhost
        description: >
          Whether the host is a superhost.
        tests:
          - accepted_values:
              values:
                [t, f]
      
      - name: created_at
        description: >
          The date the host joined Airbnb.
        tests:
          - not_null

      - name: updated_at
        description: >
          The date the host's profile was last updated.
        tests:
          - not_null
  
  - name: dim_listings_with_hosts
    tests:
      - dbt_expectations.expect_table_row_count_to_equal_other_table:
          compare_model: source('sandbox_product_engineering', 'listings')
    
    columns:
      - name: price
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: number
          - dbt_expectations.expect_column_quantile_values_to_be_between:
              quantile: .99
              min_value: 50
              max_value: 1000
          - dbt_expectations.expect_column_max_to_be_between:
              max_value: 5000
              config:
                severity: warn


